# Generated by Django 5.1.7 on 2025-07-05 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_alter_atbat_actual_player_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atbat',
            name='inning',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atbats', to='games.inning'),
        ),
        migrations.AlterField(
            model_name='inning',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='innings', to='games.game'),
        ),
        migrations.AlterField(
            model_name='pitch',
            name='at_bats',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pitches', to='games.atbat'),
        ),
    ]
