# Generated by Django 5.1.7 on 2025-07-07 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_rename_result_atbat_main_result_atbat_full_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='atbat',
            name='pitcher',
            field=models.CharField(default='투수', max_length=5),
        ),
        migrations.AlterField(
            model_name='atbat',
            name='actual_player',
            field=models.CharField(default='타자', max_length=20),
        ),
    ]
