# Generated by Django 5.1.7 on 2025-07-07 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_atbat_pitcher_alter_atbat_actual_player'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atbat',
            name='pitcher',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
