# Generated by Django 5.1.7 on 2025-07-09 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0008_alter_atbat_main_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='atbat',
            name='on_base',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='atbat',
            name='out',
            field=models.CharField(max_length=3, null=True),
        ),
    ]
