# Generated by Django 5.1.7 on 2025-07-09 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0009_atbat_on_base_atbat_out'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atbat',
            name='out',
        ),
    ]
