# Generated by Django 5.1.7 on 2025-07-09 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0010_remove_atbat_out'),
    ]

    operations = [
        migrations.AddField(
            model_name='atbat',
            name='out',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='atbat',
            name='score',
            field=models.CharField(max_length=6, null=True),
        ),
    ]
