# Generated by Django 5.1.7 on 2025-07-09 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0013_remove_player_player_code'),
    ]

    operations = [
    ]
