# Generated by Django 5.1.7 on 2025-07-09 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0014_auto_20250709_1332'),
    ]

    operations = [
        migrations.AddField(
            model_name='atbat',
            name='strike_zone',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
