# Generated by Django 5.1.7 on 2025-07-28 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0016_alter_atbat_main_result_alter_pitch_event_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='pcode',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
