# Generated by Django 5.1.7 on 2025-07-18 07:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('games', '0016_alter_atbat_main_result_alter_pitch_event_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hits', models.IntegerField(default=0)),
                ('at_bats', models.IntegerField(default=0)),
                ('walks', models.IntegerField(default=0)),
                ('strikeouts', models.IntegerField(default=0)),
                ('home_runs', models.IntegerField(default=0)),
                ('doubles', models.IntegerField(default=0)),
                ('triples', models.IntegerField(default=0)),
                ('game', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='games.game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.player')),
            ],
        ),
        migrations.CreateModel(
            name='Pitcher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('innings_pitched', models.FloatField(default=0.0)),
                ('earned_runs', models.IntegerField(default=0)),
                ('strikeouts', models.IntegerField(default=0)),
                ('walks', models.IntegerField(default=0)),
                ('game', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='games.game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.player')),
            ],
        ),
    ]
