# Generated by Django 5.1.7 on 2025-07-18 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batter',
            name='game',
        ),
    ]
