# Generated by Django 5.1.7 on 2025-07-18 07:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0016_alter_atbat_main_result_alter_pitch_event_and_more'),
        ('players', '0003_remove_pitcher_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='batter',
            name='player_name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='pitcher',
            name='player_name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='batter',
            name='at_bats',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='batter',
            name='doubles',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='batter',
            name='hits',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='batter',
            name='home_runs',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='batter',
            name='strikeouts',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='batter',
            name='triples',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='batter',
            name='walks',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='pitcher',
            name='earned_runs',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='pitcher',
            name='innings_pitched',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='pitcher',
            name='player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='games.player'),
        ),
        migrations.AlterField(
            model_name='pitcher',
            name='strikeouts',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='pitcher',
            name='walks',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
