# Generated by Django 5.1.7 on 2025-07-22 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0004_batter_player_name_pitcher_player_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='batter',
            old_name='at_bats',
            new_name='ab',
        ),
        migrations.RenameField(
            model_name='batter',
            old_name='hits',
            new_name='games',
        ),
        migrations.RenameField(
            model_name='batter',
            old_name='home_runs',
            new_name='homeruns',
        ),
        migrations.RenameField(
            model_name='pitcher',
            old_name='earned_runs',
            new_name='doubles',
        ),
        migrations.RenameField(
            model_name='pitcher',
            old_name='innings_pitched',
            new_name='innings',
        ),
        migrations.RemoveField(
            model_name='batter',
            name='player_name',
        ),
        migrations.RemoveField(
            model_name='pitcher',
            name='player_name',
        ),
        migrations.AddField(
            model_name='batter',
            name='pa',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='batter',
            name='singles',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='pitcher',
            name='games',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='pitcher',
            name='homeruns',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='pitcher',
            name='pa',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='pitcher',
            name='singles',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='pitcher',
            name='triples',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
