# Generated by Django 5.1.7 on 2025-07-22 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0005_rename_at_bats_batter_ab_rename_hits_batter_games_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='batter',
            name='play',
            field=models.IntegerField(default=0),
        ),
    ]
