# Generated by Django 5.1.7 on 2025-07-22 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0006_batter_play'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batter',
            name='play',
        ),
    ]
