# Generated by Django 5.1.7 on 2025-07-22 22:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0016_alter_atbat_main_result_alter_pitch_event_and_more'),
        ('players', '0008_alter_batter_ab_alter_batter_doubles_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batter',
            name='ab',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='batter',
            name='doubles',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='batter',
            name='games',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='batter',
            name='homeruns',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='batter',
            name='pa',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='batter',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.player'),
        ),
        migrations.AlterField(
            model_name='batter',
            name='singles',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='batter',
            name='strikeouts',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='batter',
            name='triples',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='batter',
            name='walks',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='pitcher',
            name='doubles',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='pitcher',
            name='homeruns',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='pitcher',
            name='innings',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='pitcher',
            name='pa',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='pitcher',
            name='player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='games.player'),
        ),
        migrations.AlterField(
            model_name='pitcher',
            name='singles',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='pitcher',
            name='strikeouts',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='pitcher',
            name='triples',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='pitcher',
            name='walks',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
