# Generated by Django 5.1.7 on 2025-07-23 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0009_alter_batter_ab_alter_batter_doubles_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pitcher',
            name='ab',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
