# Generated by Django 5.1.7 on 2025-07-29 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0010_pitcher_ab'),
    ]

    operations = [
        migrations.AddField(
            model_name='batter',
            name='babip',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='batter',
            name='war',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='batter',
            name='wrc',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='pitcher',
            name='era',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='pitcher',
            name='l',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='pitcher',
            name='sv',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='pitcher',
            name='w',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='pitcher',
            name='war',
            field=models.FloatField(default=0.0, null=True),
        ),
    ]
