# Generated by Django 5.1.7 on 2025-08-20 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0011_batter_babip_batter_war_batter_wrc_pitcher_era_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='batter',
            name='season',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pitcher',
            name='season',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
