# Generated by Django 5.1.7 on 2025-08-22 21:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0012_batter_season_pitcher_season'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatterRecent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ab', models.IntegerField(default=0)),
                ('hits', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batter', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='players.batter')),
            ],
        ),
    ]
