# Generated by Django 5.1.7 on 2025-09-19 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0013_batterrecent'),
    ]

    operations = [
        migrations.AddField(
            model_name='batter',
            name='baserunning_raa',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='batter',
            name='batting_raa',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='batter',
            name='defensive_raa',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='batter',
            name='fielding_raa',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='batter',
            name='offensive_raa',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='batter',
            name='total_raa',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='batter',
            name='total_raa_percentile',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='batter',
            name='total_raa_rank',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
