# Generated by Django 5.1.7 on 2025-09-20 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0014_batter_baserunning_raa_batter_batting_raa_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='batter',
            old_name='total_raa_rank',
            new_name='baserunning_raa_percentile',
        ),
        migrations.AddField(
            model_name='batter',
            name='batting_raa_percentile',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='batter',
            name='defensive_raa_percentile',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='batter',
            name='fielding_raa_percentile',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='batter',
            name='offensive_raa_percentile',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
