# Generated by Django 5.1.7 on 2025-06-01 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('status', models.CharField(default='scheduled', max_length=20)),
                ('dh', models.IntegerField(default=0)),
                ('score', models.CharField(max_length=10, null=True)),
                ('date', models.DateField()),
                ('time', models.CharField(default='1830', max_length=5, null=True)),
                ('home_team', models.CharField(max_length=5)),
                ('away_team', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=20)),
                ('position', models.CharField(max_length=10, null=True)),
                ('player_code', models.CharField(max_length=10, null=True)),
                ('team_id', models.CharField(max_length=5)),
                ('player_bdate', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Inning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inning_number', models.IntegerField()),
                ('half', models.CharField(max_length=5, null=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='relay.game')),
            ],
        ),
        migrations.CreateModel(
            name='AtBat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bat_order', models.IntegerField(null=True)),
                ('result', models.CharField(max_length=255, null=True)),
                ('appearance_num', models.IntegerField(default=1)),
                ('inning', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='relay.inning')),
                ('actual_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actual_atbats', to='relay.player')),
                ('original_player', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='original_atbats', to='relay.player')),
            ],
        ),
        migrations.CreateModel(
            name='Pitch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pitch_num', models.IntegerField(null=True)),
                ('pitch_type', models.CharField(max_length=50, null=True)),
                ('speed', models.FloatField(null=True)),
                ('count', models.CharField(max_length=10, null=True)),
                ('pitch_result', models.CharField(max_length=50, null=True)),
                ('at_bats', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='relay.atbat')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerTeamHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_year', models.CharField(max_length=5, null=True)),
                ('end_year', models.CharField(max_length=5, null=True)),
                ('is_current_team', models.BooleanField(default=False)),
                ('team_id', models.CharField(max_length=5)),
                ('move_index', models.IntegerField(default=0)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='relay.player')),
            ],
        ),
    ]
