# Generated by Django 5.1.7 on 2025-05-17 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('team_name', models.CharField(blank=True, max_length=100, null=True)),
                ('team_logo', models.CharField(blank=True, max_length=255, null=True)),
                ('field', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
