# Generated by Django 5.1.7 on 2025-09-06 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_alter_team_consecutive_streak_alter_team_losses_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='tie',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
