# Generated by Django 5.1.7 on 2025-09-06 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0004_team_tie'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='losses',
            new_name='loses',
        ),
    ]
